### ISSUE TITLE
SS & MISO swapped on 32U4

### ISSUE THREAD

**Issue by uChip** [sparkfun/Pro_Micro#2]
From the Pro Micro schematic it appears that SS & MISO pins are swapped on the ATMEGA32U4 ucontroller component in the Testing library.  According to the Atmel data sheet pin 8 should be PB0(SS) and pin 11 should be PB3(MISO).  Note this appears to be an issue with library component pin names only.  Schematic signal names and use appear to be correct.

This has caused a couple of questions in the forum: https://forum.sparkfun.com/viewtopic.php?f=14&t=41432

Thanks,
Chip

**Comment by BrentWilkins** [comment]
Correct.  This is a know, kind of fixed, issue.  Please refer to issue #1.  Look at this branch: https://github.com/sparkfun/Pro_Micro/tree/v13.1_3.3V for a corrected version.
