### ISSUE TITLE
OC4x Pins are incorrectly marked on the Graphical Datasheet

### ISSUE THREAD

**Issue by ghost** [sparkfun/Pro_Micro#3]
The datasheet correctly lists `OC4D` as on `PD7` (pin 6 on the Pro Micro), but it gets the pins for `OC3A` and `OC3B` wrong:

- `OC4A` is on `PC7` (not broken out on the Pro Micro), not pin 5 as listed in the datasheet (which in reality has `OC4A`'s complementary output).
- `OC4B` is on `PB6` (pin 10 on the Pro Micro), not pin 9 as listed in the datasheet (which in reality has `OC4B`'s complementary output).

(This can all be verified in section 10.3 (page 70) of the [ATmega16/32U4 Full Datasheet](http://www.atmel.com/Images/Atmel-7766-8-bit-AVR-ATmega16U4-32U4_Datasheet.pdf))

I discovered this issue while creating a library to generate high-speed PWM (up to 250kHz!) using the 32u4's cool ability to clock TC4 from the chip's bilt-in PLL. So in addition to creating a headache troubleshooting PWM hacking code, it also is misleading for potential buyers in that it looks like all 3 of TC4's Output Compare units are broken out when in fact only 2 are directly (aside from through complimentary ouputs which are kinda a hackish solution)

Anyways, all this to say, pls fix this in the graphical datasheet!

_As an aside, given that high-speed PWM is one of (IMO) the top 5 coolest features of the ATmega32u4, it would be cool if you someday released a tiny Atmega32u4-based board that broke out all 6 outputs (all 3 regular and inverted) for the TC4-based PWMs. This would enable all sorts of cool applications, like directly controlling FETs for a homebrew RGB LED sync buck driver, or homebrew 3-phase BLDC drivers, a kinda hackish 3-output SMPS, and many more possibilities! My own project only needs 2 HSPWMs, so I got lucky, but I think a microcontroller board with 3 high-speed PWMs, inverted outputs, and dead-time generation could be a big selling feature!_

**Comment by mshorter** [comment]
All fixed, thanks for the feedback.

**Comment by ghost** [comment]
thanks for fixing, looks much better now!
Sorry to be picky, but would you be able to push the changed files to github as well? i like grabbing info like this from the source and I feel like I'll probably forget in the future to download them from the website

**Comment by ToniCorinne** [comment]
@dn3s  they have been pushed to the repo. Thanks for your patience!

**Comment by ghost** [comment]
thanks!
