### ISSUE TITLE
Export of dimensions from eagle files

### ISSUE THREAD

**Issue by joesphan** [sparkfun/Pro_Micro#5]
Hello! I do not have eagle, could someone grab the dimensions for me?
thanks in advance

**Comment by bboyho** [comment]
Hi,

The dimensions are listed on the respective product pages under the Features tab. However, I have added the board dimensions to the product page and hookup guide for future reference. 

The Pro Micro is **1.30"x0.70"**. Note that the USB connector adds a small bit of length to the board so the total length is about **1.37"**. Enjoy! =) 

[![Pro Micro Board Dimensions](https://cdn.sparkfun.com/r/600-600/assets/learn_tutorials/1/2/1/SparkFun_Pro_Micro_Board_Dimensions.png)](https://cdn.sparkfun.com/assets/learn_tutorials/1/2/1/SparkFun_Pro_Micro_Board_Dimensions.png)
