### ISSUE TITLE
USB-C Connector Source

### ISSUE THREAD

**Issue by Gigahawk** [sparkfun/Pro_Micro#7]
What's the source for the USB-C connector?
There doesn't seem to be a library available with the package being used.
I'm looking to get the 3D model for it.

**Comment by nseidle** [comment]
[Datasheet](https://cdn.sparkfun.com/assets/8/6/b/4/5/A40-00119-A52-12.pdf) from [connector page](https://www.sparkfun.com/products/15111) should get you what you need.
