### ISSUE TITLE
Pin out D+/D-?

### ISSUE THREAD

**Issue by myst729** [sparkfun/Pro_Micro#8]
Is it possible to pin out D+/D-? Want to connect pro micro to a USB Type-C breakout board.

**Comment by ardasysmic** [comment]
[USB4110-GF-A.zip](https://github.com/sparkfun/Pro_Micro/files/6101126/USB4110-GF-A.zip)

Yes, is same. For example with this library for Eagle

![image](https://user-images.githubusercontent.com/32659291/110317671-77890a80-7fda-11eb-90f4-3a855a302625.png)

**Comment by myst729** [comment]
@ardasysmic Yes, I know what you mean. Currently I take off the micro-usb connector on Pro Micro, and fly lines to the type-c breakout board. I'm requesting to pin out the D+/D- like normal GPIOs. Something like this:

![image](https://user-images.githubusercontent.com/519733/110414745-75eb3f80-80cb-11eb-8259-f183249073c5.png)

**Comment by nseidle** [comment]
A good idea that has been implemented on the newer [Pro Micro C](https://www.sparkfun.com/products/15795):

![image](https://user-images.githubusercontent.com/117102/110546373-9cb96e00-80eb-11eb-8357-44a198940e5b.png)

We don't have plans to update the microB version of this board so I'm closing out issue.
